Venus-Hero/config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/contact'

end

Venus-Hero/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Venus-Hero/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

Venus-Hero/app/helpers/application_helper.rb
module ApplicationHelper
end

Venus-Hero/app/helpers/pages_helper.rb
module PagesHelper
end

Venus-Hero/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VenusHero</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
          
</head>
<body>
<nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Venus Hero</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#"><i class="mdi-action-view-list"></i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="#"><i class="mdi-action-view-list"></i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
      </ul>
    </div>
  </nav>

<div class="row">
	<div class="col m10 offset-m1">
		<%= yield %>		
	</div>
</div>

</body>
</html>

Venus-Hero/app/views/pages/about.html.erb
<h3>About Me</h3>

<div class="card z-depth-3">
	<div class="card-content">
		
		<div class="col m6 ">
			<a class="twitter-timeline" href="https://twitter.com/VenusIzadi" data-widget-id="603086080754188290">Tweets by @VenusIzadi</a> 
		</div>
		
		<div class="col m6 row valign-wrapper card-panel grey lighten-5 z-depth-1">
			<div class="col m3">
				<%= image_tag "avatar.jpg", class: "circle responsive-img" %>
				</div>
				<div class="col m9">
					<span class="black-text">
							I don't know what to say. Let the world tell you more... :)
					</span>
				</div>
		</div>
	</div>
</div>
</div>

Venus-Hero/app/views/pages/contact.html.erb
<h3>Contact Us</h3>

<div class="card z-depth-3">
	<div class="card-content">
		<p>Do you wanna talk? Find me on the map and we can have some drinks</p>
		<br/>
		<div id="map-canvas"></div>		
	</div>
</div>



<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
  function initialize() {
    var mapCanvas = document.getElementById('map-canvas');
    var mapOptions = {
      center: new google.maps.LatLng(-37.81, 144.96),
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas, mapOptions);
    var marker = new google.maps.Marker({
    	position: new google.maps.LatLng(-37.81, 144.96),
    	title: "Here is Melbourne!"
    });
    marker.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>